[package]
name = "camera_pic_copy"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
crossbeam-channel = "0.5.14"
serde_json = "1.0.140"
parking_lot = "0.12.3"
ctrlc = "3.4.6"